volumes:
  expenses_data: {}

services:
  expenses_db:
    image: postgres:latest
    container_name: expenses_db
    environment:
      POSTGRES_USER: expenses
      POSTGRES_PASSWORD: expenses
      PGDATA: expenses_data
      POSTGRES_DB: expenses
    ports:
      - 15000:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expenses"]
      interval: 20s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - expenses_data:/var/lib/postgresql/data
